---
- name: Instalando o container runtime
  hosts: all
  tasks:
    - name: Configurando modulos do kernel requeridos.

      ansible.builtin.copy:
        src: ./k8s.conf
        dest: /etc/modules-load.d/k8s.conf
        mode: '644'
    
    - name: Adicionando o modulo overlay
      modprobe:
        name: overlay br_netfilter
        state: present

    - name: Adicionando o modulo br_netfilter
      modprobe:
        name: br_netfilter
        state: present

    - name: COnfigurando o sysctl
      ansible.builtin.copy:
        src: ./k8s-cri.conf
        dest:  /etc/sysctl.d/k8s.conf
        mode: '644'
    
    - name: Aplicando os parametros do sysctl
      ansible.builtin.command: "sysctl --system"

    - name: Adicionando chave gpg
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    
    - name: Adicionando o repositorio para instalar o containerd
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/debian jammy stable
        state: present
    
    - name: Instalando o containerd
      ansible.builtin.apt:
        name: containerd.io
        update_cache: yes

    - name: Criando o arquivo de configuração do containerd
      ansible.builtin.shell: containerd config default > /etc/containerd/config.toml

    - name: Alterando o arquivo de configuração
      ansible.builtin.command: sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

    - name: Reiniciando o containerd
      ansible.builtin.service:
        name: containerd
        state: restarted
    
    - name: Instalando o kubeadm, kubelet e kubectl
      hosts: all
      tasks:
        - name: Instalando pré-requisitos
          ansible.builtin.apt:
            pkg:
              - apt-transport-https 
              - ca-certificates 
              - curl
            state: present
        
        - name: Baixando o chave do repositórios de pacotes do Kubernetes
          ansible.builtin.apt_key:
            url: deb https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
            state: present
        
        - name: Repósitorio para instalação do kubeadm
          ansible.builtin.apt_repository:
            repo: deb https://pkgs.k8s.io/core:/stable:/v1.28/deb/ jammy stable
            state: present

        - name: Instalando os pacotes do kubernetes
          ansible.builtin.apt:
            pkg:
              - kubelet 
              - kubeadm 
              - kubectl
            state: present
        

      
      
        
